// Copyright 2023 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image -i abelone.png -f rgb565`

#pragma once

#include <qp.h>

extern const uint32_t font_abelone_length;
extern const uint8_t  font_abelone[26109];
