#!/bin/bash

# Utility script to compile both halves at once (with EE_HANDS)

KB=elpekenin/access
KM=elpekenin

for SIDE in left right
do
    qmk compile -kb $KB -km $KM --compiledb -e MAKECMDGOALS=uf2-split-$SIDE > errors.log 2>&1 -e TARGET=$SIDE || (cat errors.log && exit 1)
done
