#let glossary = (
  (
    key: "ack",
    short: "ACK",
    long: "Acknowledgement",
    // description: "Mensaje enviado para confirmar la recepción de uno anterior",
  ),
  (
    key: "ble",
    short: "BLE",
    long: "Bluetooth Low Energy",
    // description: "Protocolo de comunicaciones inalámbricas",
  ),
  (
    key: "cli",
    short: "CLI",
    long: "Command Line Interface",
    // description: "Programa diseñado para ser usado en una terminal",
  ),
  (
    key: "cs",
    short: "CS",
    long: "Chip select",
    // description: "Señal de control en SPI",
  ),
  (
    key: "dc",
    short: "DC",
    long: "Data/Command",
    // description: "Señal de gestión en pantallas SPI",
  ),
  (
    key: "gpio",
    short: "GPIO",
    long: "General Purpose Input/Output",
    // description: "Pin de entrada/salida",
  ),
  (
    key: "hid",
    short: "HID",
    long: "Human Interface Device",
    // description: "Especificación USB para dispositivos de interfaz humana",
  ),
  (
    key: "i2c",
    short: "I2C",
    long: "Inter Integrated Circuit",
    // description: "Protocolo de comunicaciones",
  ),
  (
    key: "ide",
    short: "IDE",
    long: "Integrated Development Environment",
  ),
  (
    key: "led",
    short: "LED",
    long: "Light Emitting Diode",
  ),
  (
    key: "lsb",
    short: "LSB",
    long: "Least Significant Byte",
  ),
  (
    key: "mcu",
    short: "MCU",
    long: "Micro Controller Unit",
  ),
  (
    key: "miso",
    short: "MISO",
    long: "Master-In Slave-Out",
    // description: "Señal de datos SPI",
  ),
  (
    key: "mosi",
    short: "MOSI",
    long: "Master-Out Slave-In",
    // description: "Señal de datos SPI",
  ),
  (
    key: "msb",
    short: "MSB",
    long: "Most Significant Byte",
  ),
  (
    key: "pcb",
    short: "PCB",
    long: "Printed Circuit Board",
  ),
  (
    key: "piso",
    short: "PISO",
    long: "Parallel-In Serial-Out",
  ),
  (
    key: "rgb",
    short: "RGB",
    long: "Red Green Blue",
    // description: "Espacio de colores",
  ),
  (
    key: "rst",
    short: "RST",
    long: "Reset",
    // description: "Señal de gestión de las pantallas",
  ),
  (
    key: "rtos",
    short: "RTOS",
    long: "Real-Time Operating System",
  ),
  (
    key: "sck",
    short: "SCK",
    long: "Serial clock",
  ),
  (
    key: "sipo",
    short: "SIPO",
    long: "Serial-In Parallel-Out",
  ),
  (
    key: "spi",
    short: "SPI",
    long: "Serial Peripheral Interface",
    // description: "Protocolo de comunicaciones",
  ),
  (
    key: "uart",
    short: "UART",
    long: "Universal Asynchronous Receiver/Transmitter",
    // description: "Protocolo de comunicaciones",
  ),
  (
    key: "usb",
    short: "USB",
    long: "Universal Serial Bus",
    // description: "Protocolo de comunicaciones",
  ),
)
