#let images = (
  android: image("images/android_keyboard.jpg"),
  anti_ghosting: image("images/anti_ghosting.png", width: 45%),
  colemak: image("images/colemak.png"),
  dvorak: image("images/dvorak.jpg"),
  dygma_raise: image("images/dygma.jpg"),
  ergodox: image("images/ergodox.jpg"),
  front: image("images/UPCT-front.jpg"),
  ghosting: image("images/ghosting.png", width: 45%),
  inverter: image("images/inverter.png"),
  layout: image("images/layout.png"),
  logitech: image("images/logitech.png"),
  manuform: image("images/manuform.jpg"),
  matrix: image("images/matrix.png", width: 45%),
  mechanography: image("images/mechanography.png"),
  model_m: image("images/model_m.png"),
  ortholinear: image("images/ortholinear.jpg"),
  piso: image("images/piso.png"),
  pull_down: image("images/pull_down.png"),
  pull_up: image("images/pull_up.png"),
  quefrency: image("images/quefrency.jpg"),
  qwerty: image("images/qwerty.jpg"),
  typewriter: image("images/typewriter.jpg"),
)
