#let images = (
  android: image("images/android_keyboard.jpg"),
  anti_ghosting: image("images/anti_ghosting.png", width: 45%),
  colemak: image("images/colemak.png"),
  dvorak: image("images/dvorak.jpg"),
  elgato: image("images/elgato.jpg", width: 30%),
  ergodox: image("images/ergodox.jpg"),
  front: image("images/UPCT-front.jpg"),
  ghosting: image("images/ghosting.png", width: 45%),
  gpio: image("images/gpio.png"),
  inverter: image("images/inverter.png", width: 50%),
  jack: image("images/jack.png"),
  keys_pcb: image("images/keys_pcb.png"),
  layout: image("images/layout.png"),
  leds: image("images/leds.png"),
  logitech: image("images/logitech.png"),
  manuform: image("images/manuform.jpg"),
  matrix: image("images/matrix.png", width: 45%),
  mcu: image("images/mcu.png"),
  mechanography: image("images/mechanography.png"),
  model_m: image("images/model_m.png"),
  ortholinear: image("images/ortholinear.jpg"),
  pcbs: image("images/pcbs.png"),
  piso: image("images/piso.png", width: 120%),
  piso_pcb: image("images/piso_pcb.png"),
  pull_down: image("images/pull_down.png"),
  pull_up: image("images/pull_up.png"),
  quefrency: image("images/quefrency.jpg"),
  qwerty: image("images/qwerty.jpg"),
  rp_pico: image("images/rp_pico.webp", width: 40%),
  rp_pico_pcb: image("images/rp_pico_pcb.png"),
  sipo: image("images/sipo.png"),
  typewriter: image("images/typewriter.jpg"),
)
