#let images = (
  android: image("images/android_keyboard.jpg"),
  anti_ghosting: image("images/anti_ghosting.png", width: 40%),
  colemak: image("images/colemak.png"),
  dvorak: image("images/dvorak.jpg"),
  elgato: image("images/elgato.jpg", width: 30%),
  ergodox: image("images/ergodox.jpg", width: 40%),
  front: image("images/UPCT-front.jpg"),
  ghosting: image("images/ghosting.png", width: 30%),
  gpio: image("images/gpio.png"),
  inverter: image("images/inverter.png", width: 45%),
  jack: image("images/jack.png", width: 30%),
  keys_pcb: image("images/keys_pcb.png", width: 52%),
  layout: image("images/layout.png", width: 60%),
  leds: image("images/leds.png"),
  logitech: image("images/logitech.png", width: 90%),
  manuform: image("images/manuform.jpg", width: 40%),
  matrix: image("images/matrix.png", width: 30%),
  mcu: image("images/mcu.png"),
  mechanography: image("images/mechanography.png", width: 70%),
  model_m: image("images/model_m.png", width: 90%),
  ortholinear: image("images/ortholinear.jpg", width: 40%),
  pcb: image("images/pcb.jpeg"),
  pcbs: image("images/pcbs.png", width: 80%),
  piso: image("images/piso.png", width: 90%),
  piso_pcb: image("images/piso_pcb.png", width: 45%),
  pull_down: image("images/pull_down.png", width: 90%),
  pull_up: image("images/pull_up.png", width: 90%),
  quefrency: image("images/quefrency.jpg", width: 40%),
  qwerty: image("images/qwerty.jpg"),
  rp_pico: image("images/rp_pico.webp", width: 40%),
  rp_pico_pcb: image("images/rp_pico_pcb.png", width: 40%),
  sipo: image("images/sipo.png"),
  typewriter: image("images/typewriter.jpg", width: 45%),
)
