#!/bin/bash

# Usage: $ gif2qgf <format>

SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# From <https://unix.stackexchange.com/questions/103920/parallelize-a-bash-for-loop>


cd $SCRIPT_PATH
subfolders="$(find $SCRIPT_PATH -type d | tail -n +2)"

for folder in $subfolders; do # Iterate all folders
    N=32 # Number of concurrent tasks. Beware, a big one could crash your computer
    (
        for file in $(ls $folder); do # Iterate all files
            ((i=i%N)); ((i++==0)) && wait
            qmk painter-convert-graphics -f $1 -i $folder/$file -o . > /dev/null &
        done
    )
done
