// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/elpekenin/access_kb/firmware/pedro.gif --output /home/elpekenin/access_kb/firmware/users/elpekenin/painter/images --format pal16 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_pedro_length;
extern const uint8_t  gfx_pedro[885789];
